export const CONFIG = {
  // DB
  NEO_PROTOCOL: 'NEO_PROTOCOL',
  NEO_HOST: 'NEO_HOST',
  NEO_PORT: 'NEO_PORT',
  NEO_USERNAME: 'NEO_USERNAME',
  NEO_PASSWORD: 'NEO_PASSWORD',
  DATABASE_NAME: 'DATABASE_NAME',
} as const;
