export const IS_NODE_TYPE = 'IS_NODE_TYPE';
export const IS_NODE_PROPERTY = 'IS_NODE_PROPERTY';
export const IS_PROPERTY_UNIQUE = 'IS_PROPERTY_UNIQUE';
export const IS_FULL_TEXT_INDEXED = 'IS_FULL_TEXT_INDEXED';

export const ANNOTATED_KEYS = 'ANNOTATED_KEYS';
