export const CONFIG = {
  // DB
  COMPOUNDS_DB_NAME: 'COMPOUNDS_DB_NAME',
  MONGO_PROTOCOL: 'MONGO_PROTOCOL',
  MONGO_USERNAME: 'MONGO_USERNAME',
  MONGO_PASSWORD: 'MONGO_PASSWORD',
  MONGO_HOST: 'MONGO_HOST',
  MONGO_PORT: 'MONGO_PORT',
} as const;
